on:
  push

jobs:
  verilator-version:
    name: Verilator version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Verilator version latest
        uses: fossi-foundation/verilator-action@move-to-js
        with:
          arguments: --version
      
      - name: Verilator version 5.034
        uses: fossi-foundation/verilator-action@move-to-js
        with:
          version: '5.034'
          arguments: --version

      - name: Verilator version 5.035 (unknown)
        uses: fossi-foundation/verilator-action@move-to-js
        continue-on-error: true
        with:
          version: '5.035'
          arguments: --version        
      
  verilator-lint:
    name: Verilator lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Verilator lint
        uses: fossi-foundation/verilator-action@move-to-js
        with:
          arguments: --lint-only test.v
          
