on:
  push

jobs:
  verilator-version:
    name: Verilator version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Verilator version
        uses: fossi-foundation/verilator-action@move-to-js
        with:
          version: 5.030
          arguments: --version
          
      - name: Verilator lint
        uses: fossi-foundation/verilator-action@move-to-js
        with:
          version: 5.030
          arguments: --lint-only test.v
          
